// <auto-generated />
using System;
using EgyNews.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyNews.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250303001653_addRoleBasedMigration")]
    partial class addRoleBasedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyNews.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EgyNews.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "The government has announced a series of new policies aimed at boosting the economy and reducing unemployment. These policies include tax cuts for small businesses, increased funding for education, and infrastructure development projects. Experts believe these measures could stimulate economic growth, but critics argue that they may lead to a higher national debt. The policies are expected to be implemented over the next two years.",
                            ImageUrl = "https://picsum.photos/600/400?random=1",
                            PublishDate = new DateTime(2025, 3, 1, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8703),
                            Title = "New Government Policies Announced"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = "The results of the national elections have been declared, with the incumbent party securing a narrow victory. The opposition has raised concerns about alleged irregularities in the voting process, but international observers have declared the elections free and fair. The new government is expected to focus on healthcare reform and climate change initiatives in its first term.",
                            ImageUrl = "https://picsum.photos/600/400?random=2",
                            PublishDate = new DateTime(2025, 3, 2, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8749),
                            Title = "Election Results Declared"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Content = "Researchers have developed a new AI model capable of predicting weather patterns with 95% accuracy. This breakthrough could revolutionize industries such as agriculture, aviation, and disaster management. The AI uses advanced machine learning algorithms to analyze vast amounts of meteorological data. Experts believe this technology could save billions of dollars annually by improving weather forecasting.",
                            ImageUrl = "https://picsum.photos/600/400?random=3",
                            PublishDate = new DateTime(2025, 2, 28, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8752),
                            Title = "New AI Breakthrough"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Content = "Apple has unveiled its latest iPhone, featuring a revolutionary camera system and enhanced battery life. The new model also includes a faster processor and improved security features. Tech enthusiasts are excited about the device, which is expected to set new standards in the smartphone industry. Pre-orders for the iPhone have already broken records, with millions of units sold within the first 24 hours.",
                            ImageUrl = "https://picsum.photos/600/400?random=4",
                            PublishDate = new DateTime(2025, 2, 27, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8754),
                            Title = "Apple Launches New iPhone"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Content = "The stock market has reached an all-time high, driven by strong corporate earnings and positive economic data. Investors are optimistic about the future, with many expecting further gains in the coming months. However, some analysts warn that the market may be overvalued and could be due for a correction. Despite these concerns, the bullish trend shows no signs of slowing down.",
                            ImageUrl = "https://picsum.photos/600/400?random=5",
                            PublishDate = new DateTime(2025, 2, 26, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8757),
                            Title = "Stock Market Hits All-Time High"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Content = "The government has introduced new tax reforms aimed at boosting small businesses and stimulating economic growth. The reforms include lower corporate tax rates, simplified filing procedures, and incentives for innovation. Small business owners have welcomed the changes, which they say will reduce their financial burden and encourage expansion. Critics, however, argue that the reforms may lead to a reduction in public services.",
                            ImageUrl = "https://picsum.photos/600/400?random=6",
                            PublishDate = new DateTime(2025, 2, 25, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8760),
                            Title = "New Tax Reforms Announced"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Content = "Scientists have made a significant breakthrough in cancer research, discovering a new treatment that targets cancer cells without harming healthy tissue. The treatment, which uses a combination of immunotherapy and gene editing, has shown promising results in early clinical trials. Researchers believe this could lead to a cure for certain types of cancer within the next decade.",
                            ImageUrl = "https://picsum.photos/600/400?random=7",
                            PublishDate = new DateTime(2025, 2, 24, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8762),
                            Title = "Breakthrough in Cancer Research"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Content = "A new variant of COVID-19 has been detected, raising concerns among health officials. The variant appears to be more contagious than previous strains, but early data suggests that existing vaccines remain effective. Governments around the world are monitoring the situation closely and considering additional measures to prevent the spread of the virus.",
                            ImageUrl = "https://picsum.photos/600/400?random=8",
                            PublishDate = new DateTime(2025, 2, 23, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8765),
                            Title = "New COVID-19 Variant Detected"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Content = "The World Cup 2023 has kicked off with thrilling matches and unexpected results. Fans around the world are glued to their screens as their favorite teams compete for the prestigious trophy. The tournament has already seen several upsets, with underdog teams defeating traditional powerhouses. The excitement is expected to build as the competition progresses.",
                            ImageUrl = "https://picsum.photos/600/400?random=9",
                            PublishDate = new DateTime(2025, 2, 22, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8767),
                            Title = "World Cup 2023 Highlights"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Content = "An athlete has set a new world record in the marathon, finishing the race in under two hours. The incredible feat has stunned the sports world and raised questions about the limits of human endurance. The runner credited their success to a rigorous training regimen and a focus on mental preparation. The record is expected to stand for years to come.",
                            ImageUrl = "https://picsum.photos/600/400?random=10",
                            PublishDate = new DateTime(2025, 2, 21, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8770),
                            Title = "New Record in Marathon"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Content = "The latest Marvel movie has broken box office records on its opening weekend, grossing over $500 million worldwide. Fans have praised the film for its stunning visuals, gripping storyline, and standout performances. The movie is expected to dominate the box office for weeks to come and has already sparked speculation about future sequels and spin-offs.",
                            ImageUrl = "https://picsum.photos/600/400?random=11",
                            PublishDate = new DateTime(2025, 2, 20, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8773),
                            Title = "New Marvel Movie Release"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Content = "The Grammy Awards 2023 saw some surprising wins and memorable performances. Artists from various genres were honored for their contributions to music, with several newcomers taking home major awards. The event was a celebration of creativity and diversity, showcasing the best of the music industry. Fans are already looking forward to next year's ceremony.",
                            ImageUrl = "https://picsum.photos/600/400?random=12",
                            PublishDate = new DateTime(2025, 2, 19, 2, 16, 51, 845, DateTimeKind.Local).AddTicks(8776),
                            Title = "Grammy Awards 2023 Winners"
                        });
                });

            modelBuilder.Entity("EgyNews.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Business And Economy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Health And Science"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "523256fa-d881-4055-b299-5ed8dd946d0e",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "fe1e5637-10db-4b6d-a47e-558474da6e95",
                            Name = "Blogger",
                            NormalizedName = "BLOGGER"
                        },
                        new
                        {
                            Id = "052ccfd3-35b6-400f-946f-a170803dd611",
                            Name = "Reader",
                            NormalizedName = "READER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EgyNews.Models.Article", b =>
                {
                    b.HasOne("EgyNews.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
