// <auto-generated />
using System;
using EgyNews.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyNews.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250306221049_addMoreDate")]
    partial class addMoreDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyNews.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EgyNews.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "The government has announced a series of new policies aimed at boosting the economy and reducing unemployment. These policies include tax cuts for small businesses, increased funding for education, and infrastructure development projects. Experts believe these measures could stimulate economic growth, but critics argue that they may lead to a higher national debt. The policies are expected to be implemented over the next two years.",
                            ImageUrl = "https://picsum.photos/600/400?random=1",
                            PublishDate = new DateTime(2025, 3, 5, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2622),
                            Title = "New Government Policies Announced"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = "The results of the national elections have been declared, with the incumbent party securing a narrow victory. The opposition has raised concerns about alleged irregularities in the voting process, but international observers have declared the elections free and fair. The new government is expected to focus on healthcare reform and climate change initiatives in its first term.",
                            ImageUrl = "https://picsum.photos/600/400?random=2",
                            PublishDate = new DateTime(2025, 3, 6, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2678),
                            Title = "Election Results Declared"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Content = "High-level diplomatic talks have begun between two neighboring countries...",
                            ImageUrl = "https://picsum.photos/600/400?random=13",
                            PublishDate = new DateTime(2025, 3, 4, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2682),
                            Title = "Diplomatic Talks Between Nations"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Content = "A new bill aimed at combating climate change has been introduced...",
                            ImageUrl = "https://picsum.photos/600/400?random=14",
                            PublishDate = new DateTime(2025, 3, 3, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2686),
                            Title = "New Legislation on Climate Change"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Content = "A major political scandal has been uncovered, involving high-ranking officials...",
                            ImageUrl = "https://picsum.photos/600/400?random=15",
                            PublishDate = new DateTime(2025, 3, 2, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2690),
                            Title = "Political Scandal Unveiled"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Content = "Researchers have developed a new AI model capable of predicting weather patterns with 95% accuracy. This breakthrough could revolutionize industries such as agriculture, aviation, and disaster management. The AI uses advanced machine learning algorithms to analyze vast amounts of meteorological data. Experts believe this technology could save billions of dollars annually by improving weather forecasting.",
                            ImageUrl = "https://picsum.photos/600/400?random=3",
                            PublishDate = new DateTime(2025, 3, 4, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2694),
                            Title = "New AI Breakthrough"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Content = "Apple has unveiled its latest iPhone, featuring a revolutionary camera system and enhanced battery life. The new model also includes a faster processor and improved security features. Tech enthusiasts are excited about the device, which is expected to set new standards in the smartphone industry. Pre-orders for the iPhone have already broken records, with millions of units sold within the first 24 hours.",
                            ImageUrl = "https://picsum.photos/600/400?random=4",
                            PublishDate = new DateTime(2025, 3, 3, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2697),
                            Title = "Apple Launches New iPhone"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Content = "A breakthrough in quantum computing has been achieved...",
                            ImageUrl = "https://picsum.photos/600/400?random=16",
                            PublishDate = new DateTime(2025, 3, 1, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2702),
                            Title = "Quantum Computing Advancements"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Content = "Experts warn of increasing cybersecurity threats...",
                            ImageUrl = "https://picsum.photos/600/400?random=17",
                            PublishDate = new DateTime(2025, 2, 28, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2705),
                            Title = "Cybersecurity Threats on the Rise"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Content = "Tech companies have introduced a range of new smart home devices...",
                            ImageUrl = "https://picsum.photos/600/400?random=18",
                            PublishDate = new DateTime(2025, 2, 27, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2709),
                            Title = "New Smart Home Devices"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Content = "Autonomous vehicles are set to revolutionize transportation...",
                            ImageUrl = "https://picsum.photos/600/400?random=19",
                            PublishDate = new DateTime(2025, 2, 26, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2713),
                            Title = "The Future of Autonomous Vehicles"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Content = "The stock market has reached an all-time high, driven by strong corporate earnings and positive economic data. Investors are optimistic about the future, with many expecting further gains in the coming months. However, some analysts warn that the market may be overvalued and could be due for a correction. Despite these concerns, the bullish trend shows no signs of slowing down.",
                            ImageUrl = "https://picsum.photos/600/400?random=5",
                            PublishDate = new DateTime(2025, 3, 2, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2717),
                            Title = "Stock Market Hits All-Time High"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Content = "The government has introduced new tax reforms aimed at boosting small businesses and stimulating economic growth. The reforms include lower corporate tax rates, simplified filing procedures, and incentives for innovation. Small business owners have welcomed the changes, which they say will reduce their financial burden and encourage expansion. Critics, however, argue that the reforms may lead to a reduction in public services.",
                            ImageUrl = "https://picsum.photos/600/400?random=6",
                            PublishDate = new DateTime(2025, 3, 1, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2721),
                            Title = "New Tax Reforms Announced"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Content = "The IMF has released its latest global economic growth forecast...",
                            ImageUrl = "https://picsum.photos/600/400?random=20",
                            PublishDate = new DateTime(2025, 2, 25, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2725),
                            Title = "Global Economic Growth Forecast"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Content = "A list of promising startups that are making waves...",
                            ImageUrl = "https://picsum.photos/600/400?random=21",
                            PublishDate = new DateTime(2025, 2, 24, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2729),
                            Title = "Startups to Watch in 2023"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Content = "Rising inflation is affecting consumer spending habits...",
                            ImageUrl = "https://picsum.photos/600/400?random=22",
                            PublishDate = new DateTime(2025, 2, 23, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2733),
                            Title = "Impact of Inflation on Consumers"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Content = "Several countries have signed new trade agreements...",
                            ImageUrl = "https://picsum.photos/600/400?random=23",
                            PublishDate = new DateTime(2025, 2, 22, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2736),
                            Title = "New Trade Agreements Signed"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Content = "Remote work is becoming the new norm for many businesses...",
                            ImageUrl = "https://picsum.photos/600/400?random=24",
                            PublishDate = new DateTime(2025, 2, 21, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2740),
                            Title = "The Rise of Remote Work"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Content = "Scientists have made a significant breakthrough in cancer research, discovering a new treatment that targets cancer cells without harming healthy tissue. The treatment, which uses a combination of immunotherapy and gene editing, has shown promising results in early clinical trials. Researchers believe this could lead to a cure for certain types of cancer within the next decade.",
                            ImageUrl = "https://picsum.photos/600/400?random=7",
                            PublishDate = new DateTime(2025, 2, 28, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2744),
                            Title = "Breakthrough in Cancer Research"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Content = "A new variant of COVID-19 has been detected, raising concerns among health officials. The variant appears to be more contagious than previous strains, but early data suggests that existing vaccines remain effective. Governments around the world are monitoring the situation closely and considering additional measures to prevent the spread of the virus.",
                            ImageUrl = "https://picsum.photos/600/400?random=8",
                            PublishDate = new DateTime(2025, 2, 27, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2749),
                            Title = "New COVID-19 Variant Detected"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Content = "Gene therapy is showing promise in treating genetic disorders...",
                            ImageUrl = "https://picsum.photos/600/400?random=25",
                            PublishDate = new DateTime(2025, 2, 20, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2753),
                            Title = "Advances in Gene Therapy"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Content = "Studies show that meditation can improve mental health...",
                            ImageUrl = "https://picsum.photos/600/400?random=26",
                            PublishDate = new DateTime(2025, 2, 19, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2756),
                            Title = "The Benefits of Meditation"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            Content = "Astronomers have made new discoveries in space...",
                            ImageUrl = "https://picsum.photos/600/400?random=27",
                            PublishDate = new DateTime(2025, 2, 18, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2761),
                            Title = "New Discoveries in Space Exploration"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Content = "Researchers are developing new vaccine technologies...",
                            ImageUrl = "https://picsum.photos/600/400?random=28",
                            PublishDate = new DateTime(2025, 2, 17, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2765),
                            Title = "The Future of Vaccines"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Content = "A new campaign aims to raise awareness about mental health...",
                            ImageUrl = "https://picsum.photos/600/400?random=29",
                            PublishDate = new DateTime(2025, 2, 16, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2768),
                            Title = "Mental Health Awareness Campaign"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Content = "Scientists have developed a new renewable energy source...",
                            ImageUrl = "https://picsum.photos/600/400?random=30",
                            PublishDate = new DateTime(2025, 2, 15, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2772),
                            Title = "Breakthrough in Renewable Energy"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Content = "The World Cup 2023 has kicked off with thrilling matches and unexpected results. Fans around the world are glued to their screens as their favorite teams compete for the prestigious trophy. The tournament has already seen several upsets, with underdog teams defeating traditional powerhouses. The excitement is expected to build as the competition progresses.",
                            ImageUrl = "https://picsum.photos/600/400?random=9",
                            PublishDate = new DateTime(2025, 2, 26, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2775),
                            Title = "World Cup 2023 Highlights"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Content = "An athlete has set a new world record in the marathon, finishing the race in under two hours. The incredible feat has stunned the sports world and raised questions about the limits of human endurance. The runner credited their success to a rigorous training regimen and a focus on mental preparation. The record is expected to stand for years to come.",
                            ImageUrl = "https://picsum.photos/600/400?random=10",
                            PublishDate = new DateTime(2025, 2, 25, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2778),
                            Title = "New Record in Marathon"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Content = "Preparations for the 2024 Olympic Games are underway...",
                            ImageUrl = "https://picsum.photos/600/400?random=31",
                            PublishDate = new DateTime(2025, 2, 14, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2782),
                            Title = "Olympic Games 2024 Preparations"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Content = "Young tennis players are making a name for themselves...",
                            ImageUrl = "https://picsum.photos/600/400?random=32",
                            PublishDate = new DateTime(2025, 2, 13, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2786),
                            Title = "Rising Stars in Tennis"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Content = "Basketball has evolved significantly over the years...",
                            ImageUrl = "https://picsum.photos/600/400?random=33",
                            PublishDate = new DateTime(2025, 2, 12, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2789),
                            Title = "The Evolution of Basketball"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Content = "Esports is gaining popularity as a competitive sport...",
                            ImageUrl = "https://picsum.photos/600/400?random=34",
                            PublishDate = new DateTime(2025, 2, 11, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2793),
                            Title = "Esports: The New Frontier"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            Content = "Sports can have a positive impact on mental health...",
                            ImageUrl = "https://picsum.photos/600/400?random=35",
                            PublishDate = new DateTime(2025, 2, 10, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2796),
                            Title = "The Impact of Sports on Mental Health"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 5,
                            Content = "Football's governing body has introduced new rules...",
                            ImageUrl = "https://picsum.photos/600/400?random=36",
                            PublishDate = new DateTime(2025, 2, 9, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2800),
                            Title = "New Rules in Football"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Content = "Women are breaking barriers in the world of sports...",
                            ImageUrl = "https://picsum.photos/600/400?random=37",
                            PublishDate = new DateTime(2025, 2, 8, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2803),
                            Title = "The Rise of Women in Sports"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Content = "The latest Marvel movie has broken box office records on its opening weekend, grossing over $500 million worldwide. Fans have praised the film for its stunning visuals, gripping storyline, and standout performances. The movie is expected to dominate the box office for weeks to come and has already sparked speculation about future sequels and spin-offs.",
                            ImageUrl = "https://picsum.photos/600/400?random=11",
                            PublishDate = new DateTime(2025, 2, 24, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2807),
                            Title = "New Marvel Movie Release"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Content = "The Grammy Awards 2023 saw some surprising wins and memorable performances. Artists from various genres were honored for their contributions to music, with several newcomers taking home major awards. The event was a celebration of creativity and diversity, showcasing the best of the music industry. Fans are already looking forward to next year's ceremony.",
                            ImageUrl = "https://picsum.photos/600/400?random=12",
                            PublishDate = new DateTime(2025, 2, 23, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2811),
                            Title = "Grammy Awards 2023 Winners"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 6,
                            Content = "Streaming services are changing the entertainment industry...",
                            ImageUrl = "https://picsum.photos/600/400?random=38",
                            PublishDate = new DateTime(2025, 2, 7, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2814),
                            Title = "The Future of Streaming Services"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            Content = "A list of the most anticipated music festivals of the year...",
                            ImageUrl = "https://picsum.photos/600/400?random=39",
                            PublishDate = new DateTime(2025, 2, 6, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2818),
                            Title = "Upcoming Music Festivals"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 6,
                            Content = "Social media is reshaping how we consume entertainment...",
                            ImageUrl = "https://picsum.photos/600/400?random=40",
                            PublishDate = new DateTime(2025, 2, 5, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2822),
                            Title = "The Impact of Social Media on Entertainment"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 6,
                            Content = "Broadway is back with a lineup of exciting new shows...",
                            ImageUrl = "https://picsum.photos/600/400?random=41",
                            PublishDate = new DateTime(2025, 2, 4, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2826),
                            Title = "New Broadway Shows to Watch"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            Content = "Independent films are gaining recognition in the industry...",
                            ImageUrl = "https://picsum.photos/600/400?random=42",
                            PublishDate = new DateTime(2025, 2, 3, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2830),
                            Title = "The Rise of Independent Films"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 6,
                            Content = "Celebrities are setting new fashion trends this season...",
                            ImageUrl = "https://picsum.photos/600/400?random=43",
                            PublishDate = new DateTime(2025, 2, 2, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2834),
                            Title = "Celebrity Fashion Trends"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            Content = "Video games have come a long way since their inception...",
                            ImageUrl = "https://picsum.photos/600/400?random=44",
                            PublishDate = new DateTime(2025, 2, 1, 0, 10, 46, 155, DateTimeKind.Local).AddTicks(2837),
                            Title = "The Evolution of Video Games"
                        });
                });

            modelBuilder.Entity("EgyNews.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Business And Economy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Health And Science"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9a3e767c-cd75-479c-8247-9a71fcfe226e",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "375753ff-4559-4dd2-ad2e-3f3ea65d7182",
                            Name = "Blogger",
                            NormalizedName = "BLOGGER"
                        },
                        new
                        {
                            Id = "8d68ce38-d40c-4e1a-807e-de0e9897183b",
                            Name = "Reader",
                            NormalizedName = "READER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EgyNews.Models.Article", b =>
                {
                    b.HasOne("EgyNews.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EgyNews.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
